name: Deploy to EKS

on:
  push:
    branches:
      - main
      - seup-brancht

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin 673084610131.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build image
      run: |
        docker build -t demo-app .

    - name: Tag image
      run: |
        docker tag demo-app:latest 673084610131.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest

    - name: Push image
      run: |
        docker push 673084610131.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster-3 --region ap-south-1

    - name: Deploy to TEST
      if: github.ref == 'refs/heads/seup-brancht'
      run: |
        kubectl apply -f k8s/test/
        kubectl rollout restart deployment/demo-app -n dev

    - name: Deploy to LIVE
      if: github.ref == 'refs/heads/main'
      run: |
        kubectl apply -f k8s/live/
        kubectl rollout restart deployment/demo-app -n prod

    - name: Verify deployment
      run: |
        kubectl get pods -A
        kubectl get svc -A